In [ ]:
%run ../../scripts/run_gifteval_config.py --config ../../configs/experiments/toto_short_uni_4096.yaml

2025-11-18 13:38:09 - INFO - Starting per-dataset execution for configs/experiments/moirai_short_uni_512.yaml
INFO:ts_toolkit.pipeline.dataset_batch_runner:Starting per-dataset execution for configs/experiments/moirai_short_uni_512.yaml
2025-11-18 13:38:09 - INFO - Results will be stored under /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809
INFO:ts_toolkit.pipeline.dataset_batch_runner:Results will be stored under /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809
2025-11-18 13:38:09 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 13:38:09 - INFO - Processing dataset 'bitbrains_fast_storage/5T' (slug: bitbrains_fast_storage_5T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bitbrains_fast_storage/5T' (slug: bitbrains_fast_storage_5T__short)

Loading base config from <REPO_ROOT>/configs/experiments/moirai_short_uni_512.yaml...

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 159.41it/s]

















1024it [00:06, 159.60it/s]


















1024it [00:06, 151.62it/s]


















1024it [00:06, 150.87it/s]


















1024it [00:06, 151.60it/s]


















1024it [00:06, 150.72it/s]


















1024it [00:06, 149.70it/s]


















1024it [00:06, 149.01it/s]


















1024it [00:06, 149.90it/s]


















1024it [00:06, 150.11it/s]

















1024it [00:06, 157.88it/s]

















1024it [00:06, 156.12it/s]

















1024it [00:06, 158.02it/s]

















1024it [00:06, 157.00it/s]

















1024it [00:06, 157.57it/s]

















1024it [00:06, 158.13it/s]

















1024it [00:06, 157.68it/s]

















1024it [00:06, 157.64it/s]

















1024it [00:06, 157.22it/s]

















1024it [00:06, 157.68it/s]

















1024it [00:06, 157.42it/s]

















1024it [00:06, 157.71it/s]

















1024it [00:06, 157.97it/s]

















1024it [00:06, 157.33it/s]

















1024it [00:06, 157.82it/s]

















1024it [00:06, 157.85it/s]

















1024it [00:06, 157.54it/s]

















1024it [00:06, 157.45it/s]

















1024it [00:06, 157.59it/s]

















1024it [00:06, 158.02it/s]

















1024it [00:06, 157.47it/s]

















1024it [00:06, 157.77it/s]

















1024it [00:06, 156.82it/s]

















1024it [00:06, 157.14it/s]

















1024it [00:06, 156.95it/s]

















1024it [00:06, 157.62it/s]

















1024it [00:06, 158.17it/s]

















1024it [00:06, 157.82it/s]

















1024it [00:06, 156.55it/s]

















1024it [00:06, 157.14it/s]

















1024it [00:06, 156.10it/s]

















1024it [00:06, 157.96it/s]

















1024it [00:06, 157.60it/s]

















968it [00:06, 156.30it/s]





/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]




















































































45000it [01:04, 697.78it/s]
2025-11-18 13:56:45 - INFO - OK saved results for 'bitbrains_fast_storage/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_fast_storage_5T__short/Moirai-GiftEval/bitbrains_fast_storage_5T__short_results.csv (1115.434s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bitbrains_fast_storage/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_fast_storage_5T__short/Moirai-GiftEval/bitbrains_fast_storage_5T__short_results.csv (1115.434s)
2025-11-18 13:56:45 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 13:56:45 - INFO - Processing dataset 'bitbrains_fast_storage/H' (slug: bitbrains_fast_storage_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bitbrains_fast_storage/H' (slug: bitbrains_fast_storage_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 151.68it/s]


















1024it [00:06, 150.55it/s]


















1024it [00:06, 151.05it/s]


















1024it [00:06, 151.14it/s]

















904it [00:06, 149.99it/s]

/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]










5000it [00:03, 1408.59it/s]
2025-11-18 13:58:45 - INFO - OK saved results for 'bitbrains_fast_storage/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_fast_storage_H__short/Moirai-GiftEval/bitbrains_fast_storage_H__short_results.csv (120.716s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bitbrains_fast_storage/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_fast_storage_H__short/Moirai-GiftEval/bitbrains_fast_storage_H__short_results.csv (120.716s)
2025-11-18 13:58:45 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 13:58:45 - INFO - Processing dataset 'bitbrains_rnd/5T' (slug: bitbrains_rnd_5T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bitbrains_rnd/5T' (slug: bitbrains_rnd_5T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 151.27it/s]

















1024it [00:06, 157.95it/s]

















1024it [00:06, 157.77it/s]

















1024it [00:06, 157.48it/s]

















1024it [00:06, 156.94it/s]

















1024it [00:06, 157.20it/s]

















1024it [00:06, 157.41it/s]

















1024it [00:06, 157.84it/s]

















1024it [00:06, 157.57it/s]

















1024it [00:06, 157.28it/s]

















1024it [00:06, 156.58it/s]

















1024it [00:06, 156.80it/s]

















1024it [00:06, 156.74it/s]


















1024it [00:06, 149.69it/s]


















1024it [00:06, 149.28it/s]


















1024it [00:06, 149.13it/s]


















1024it [00:06, 148.98it/s]











592it [00:03, 156.86it/s]





/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]
































18000it [00:25, 695.17it/s]
2025-11-18 14:06:14 - INFO - OK saved results for 'bitbrains_rnd/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_rnd_5T__short/Moirai-GiftEval/bitbrains_rnd_5T__short_results.csv (448.889s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bitbrains_rnd/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_rnd_5T__short/Moirai-GiftEval/bitbrains_rnd_5T__short_results.csv (448.889s)
2025-11-18 14:06:14 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:06:14 - INFO - Processing dataset 'bitbrains_rnd/H' (slug: bitbrains_rnd_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bitbrains_rnd/H' (slug: bitbrains_rnd_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 158.90it/s]

















976it [00:06, 157.81it/s]

/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]




2000it [00:01, 1385.77it/s]
2025-11-18 14:07:03 - INFO - OK saved results for 'bitbrains_rnd/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_rnd_H__short/Moirai-GiftEval/bitbrains_rnd_H__short_results.csv (48.620s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bitbrains_rnd/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bitbrains_rnd_H__short/Moirai-GiftEval/bitbrains_rnd_H__short_results.csv (48.620s)
2025-11-18 14:07:03 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:03 - INFO - Processing dataset 'bizitobs_l2c/5T' (slug: bizitobs_l2c_5T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bizitobs_l2c/5T' (slug: bizitobs_l2c_5T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

140it [00:00, 152.02it/s]


140it [00:00, 253.41it/s]
2025-11-18 14:07:08 - INFO - OK saved results for 'bizitobs_l2c/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bizitobs_l2c_5T__short/Moirai-GiftEval/bizitobs_l2c_5T__short_results.csv (5.022s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bizitobs_l2c/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bizitobs_l2c_5T__short/Moirai-GiftEval/bizitobs_l2c_5T__short_results.csv (5.022s)
2025-11-18 14:07:08 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:08 - INFO - Processing dataset 'bizitobs_l2c/H' (slug: bizitobs_l2c_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'bizitobs_l2c/H' (slug: bizitobs_l2c_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

42it [00:00, 145.71it/s]

42it [00:00, 1063.30it/s]
2025-11-18 14:07:10 - INFO - OK saved results for 'bizitobs_l2c/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bizitobs_l2c_H__short/Moirai-GiftEval/bizitobs_l2c_H__short_results.csv (2.276s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'bizitobs_l2c/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/bizitobs_l2c_H__short/Moirai-GiftEval/bizitobs_l2c_H__short_results.csv (2.276s)
2025-11-18 14:07:10 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:10 - INFO - Processing dataset 'ett1/15T' (slug: ett1_15T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett1/15T' (slug: ett1_15T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

140it [00:00, 153.49it/s]


140it [00:01, 126.07it/s]
2025-11-18 14:07:16 - INFO - OK saved results for 'ett1/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_15T__short/Moirai-GiftEval/ett1_15T__short_results.csv (5.641s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett1/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_15T__short/Moirai-GiftEval/ett1_15T__short_results.csv (5.641s)
2025-11-18 14:07:16 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:16 - INFO - Processing dataset 'ett1/D' (slug: ett1_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett1/D' (slug: ett1_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

21it [00:00, 134.03it/s]

21it [00:00, 1195.15it/s]
2025-11-18 14:07:18 - INFO - OK saved results for 'ett1/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_D__short/Moirai-GiftEval/ett1_D__short_results.csv (1.699s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett1/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_D__short/Moirai-GiftEval/ett1_D__short_results.csv (1.699s)
2025-11-18 14:07:18 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:18 - INFO - Processing dataset 'ett1/H' (slug: ett1_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett1/H' (slug: ett1_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

140it [00:00, 155.23it/s]


140it [00:00, 424.98it/s]
2025-11-18 14:07:22 - INFO - OK saved results for 'ett1/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_H__short/Moirai-GiftEval/ett1_H__short_results.csv (4.681s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett1/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_H__short/Moirai-GiftEval/ett1_H__short_results.csv (4.681s)
2025-11-18 14:07:22 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:22 - INFO - Processing dataset 'ett1/W' (slug: ett1_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett1/W' (slug: ett1_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

14it [00:00, 134.44it/s]

14it [00:00, 1163.65it/s]
2025-11-18 14:07:24 - INFO - OK saved results for 'ett1/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_W__short/Moirai-GiftEval/ett1_W__short_results.csv (1.445s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett1/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett1_W__short/Moirai-GiftEval/ett1_W__short_results.csv (1.445s)
2025-11-18 14:07:24 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:24 - INFO - Processing dataset 'ett2/15T' (slug: ett2_15T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett2/15T' (slug: ett2_15T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

140it [00:00, 155.86it/s]


140it [00:01, 130.48it/s]
2025-11-18 14:07:29 - INFO - OK saved results for 'ett2/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_15T__short/Moirai-GiftEval/ett2_15T__short_results.csv (5.457s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett2/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_15T__short/Moirai-GiftEval/ett2_15T__short_results.csv (5.457s)
2025-11-18 14:07:29 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:29 - INFO - Processing dataset 'ett2/D' (slug: ett2_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett2/D' (slug: ett2_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

21it [00:00, 140.69it/s]

21it [00:00, 1191.32it/s]
2025-11-18 14:07:31 - INFO - OK saved results for 'ett2/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_D__short/Moirai-GiftEval/ett2_D__short_results.csv (1.977s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett2/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_D__short/Moirai-GiftEval/ett2_D__short_results.csv (1.977s)
2025-11-18 14:07:31 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:31 - INFO - Processing dataset 'ett2/H' (slug: ett2_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett2/H' (slug: ett2_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

140it [00:00, 154.69it/s]


140it [00:00, 418.58it/s]
2025-11-18 14:07:36 - INFO - OK saved results for 'ett2/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_H__short/Moirai-GiftEval/ett2_H__short_results.csv (4.690s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett2/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_H__short/Moirai-GiftEval/ett2_H__short_results.csv (4.690s)
2025-11-18 14:07:36 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:36 - INFO - Processing dataset 'ett2/W' (slug: ett2_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'ett2/W' (slug: ett2_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

14it [00:00, 130.56it/s]

14it [00:00, 1116.78it/s]
2025-11-18 14:07:37 - INFO - OK saved results for 'ett2/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_W__short/Moirai-GiftEval/ett2_W__short_results.csv (1.443s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'ett2/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/ett2_W__short/Moirai-GiftEval/ett2_W__short_results.csv (1.443s)
2025-11-18 14:07:37 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:37 - INFO - Processing dataset 'jena_weather/10T' (slug: jena_weather_10T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'jena_weather/10T' (slug: jena_weather_10T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

420it [00:02, 158.07it/s]


420it [00:02, 164.69it/s]
2025-11-18 14:07:50 - INFO - OK saved results for 'jena_weather/10T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_10T__short/Moirai-GiftEval/jena_weather_10T__short_results.csv (12.990s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'jena_weather/10T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_10T__short/Moirai-GiftEval/jena_weather_10T__short_results.csv (12.990s)
2025-11-18 14:07:50 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:50 - INFO - Processing dataset 'jena_weather/D' (slug: jena_weather_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'jena_weather/D' (slug: jena_weather_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

42it [00:00, 143.92it/s]

42it [00:00, 1457.99it/s]
2025-11-18 14:07:52 - INFO - OK saved results for 'jena_weather/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_D__short/Moirai-GiftEval/jena_weather_D__short_results.csv (2.024s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'jena_weather/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_D__short/Moirai-GiftEval/jena_weather_D__short_results.csv (2.024s)
2025-11-18 14:07:52 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:07:52 - INFO - Processing dataset 'jena_weather/H' (slug: jena_weather_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'jena_weather/H' (slug: jena_weather_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

399it [00:02, 156.70it/s]


399it [00:00, 686.50it/s]
2025-11-18 14:08:03 - INFO - OK saved results for 'jena_weather/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_H__short/Moirai-GiftEval/jena_weather_H__short_results.csv (10.917s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'jena_weather/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/jena_weather_H__short/Moirai-GiftEval/jena_weather_H__short_results.csv (10.917s)
2025-11-18 14:08:03 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:08:03 - INFO - Processing dataset 'electricity/15T' (slug: electricity_15T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'electricity/15T' (slug: electricity_15T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 150.43it/s]


















1024it [00:06, 149.10it/s]


















1024it [00:06, 150.73it/s]

















1024it [00:06, 157.59it/s]

















1024it [00:06, 157.51it/s]

















1024it [00:06, 157.27it/s]

















1024it [00:06, 157.32it/s]





232it [00:01, 155.11it/s]
















7400it [01:51, 66.67it/s]
2025-11-18 14:12:49 - INFO - OK saved results for 'electricity/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_15T__short/Moirai-GiftEval/electricity_15T__short_results.csv (285.839s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'electricity/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_15T__short/Moirai-GiftEval/electricity_15T__short_results.csv (285.839s)
2025-11-18 14:12:49 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:12:49 - INFO - Processing dataset 'electricity/D' (slug: electricity_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'electricity/D' (slug: electricity_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 152.70it/s]















826it [00:05, 150.51it/s]





1850it [00:01, 1342.47it/s]
2025-11-18 14:13:24 - INFO - OK saved results for 'electricity/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_D__short/Moirai-GiftEval/electricity_D__short_results.csv (34.494s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'electricity/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_D__short/Moirai-GiftEval/electricity_D__short_results.csv (34.494s)
2025-11-18 14:13:24 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:13:24 - INFO - Processing dataset 'electricity/H' (slug: electricity_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'electricity/H' (slug: electricity_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 159.43it/s]


















1024it [00:06, 150.53it/s]


















1024it [00:06, 150.13it/s]


















1024it [00:06, 150.05it/s]


















1024it [00:06, 149.54it/s]


















1024it [00:06, 149.60it/s]


















1024it [00:06, 150.45it/s]





232it [00:01, 154.86it/s]
















7400it [00:31, 234.98it/s]
2025-11-18 14:16:48 - INFO - OK saved results for 'electricity/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_H__short/Moirai-GiftEval/electricity_H__short_results.csv (204.778s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'electricity/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_H__short/Moirai-GiftEval/electricity_H__short_results.csv (204.778s)
2025-11-18 14:16:48 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:16:48 - INFO - Processing dataset 'electricity/W' (slug: electricity_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'electricity/W' (slug: electricity_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 158.85it/s]




86it [00:00, 99.54it/s]


/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]

1110it [00:00, 1535.18it/s]
2025-11-18 14:17:04 - INFO - OK saved results for 'electricity/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_W__short/Moirai-GiftEval/electricity_W__short_results.csv (16.120s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'electricity/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/electricity_W__short/Moirai-GiftEval/electricity_W__short_results.csv (16.120s)
2025-11-18 14:17:04 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:17:04 - INFO - Processing dataset 'hierarchical_sales/D' (slug: hierarchical_sales_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'hierarchical_sales/D' (slug: hierarchical_sales_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

826it [00:05, 158.25it/s]



826it [00:00, 1294.09it/s]
2025-11-18 14:17:20 - INFO - OK saved results for 'hierarchical_sales/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/hierarchical_sales_D__short/Moirai-GiftEval/hierarchical_sales_D__short_results.csv (15.440s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'hierarchical_sales/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/hierarchical_sales_D__short/Moirai-GiftEval/hierarchical_sales_D__short_results.csv (15.440s)
2025-11-18 14:17:20 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:17:20 - INFO - Processing dataset 'hierarchical_sales/W' (slug: hierarchical_sales_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'hierarchical_sales/W' (slug: hierarchical_sales_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

472it [00:03, 157.19it/s]


472it [00:00, 1538.74it/s]
2025-11-18 14:17:27 - INFO - OK saved results for 'hierarchical_sales/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/hierarchical_sales_W__short/Moirai-GiftEval/hierarchical_sales_W__short_results.csv (7.263s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'hierarchical_sales/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/hierarchical_sales_W__short/Moirai-GiftEval/hierarchical_sales_W__short_results.csv (7.263s)
2025-11-18 14:17:27 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:17:27 - INFO - Processing dataset 'kdd_cup_2018_with_missing/D' (slug: kdd_cup_2018_with_missing_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'kdd_cup_2018_with_missing/D' (slug: kdd_cup_2018_with_missing_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

540it [00:03, 157.59it/s]


540it [00:00, 1375.41it/s]
2025-11-18 14:17:38 - INFO - OK saved results for 'kdd_cup_2018_with_missing/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/kdd_cup_2018_with_missing_D__short/Moirai-GiftEval/kdd_cup_2018_with_missing_D__short_results.csv (10.551s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'kdd_cup_2018_with_missing/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/kdd_cup_2018_with_missing_D__short/Moirai-GiftEval/kdd_cup_2018_with_missing_D__short_results.csv (10.551s)
2025-11-18 14:17:38 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:17:38 - INFO - Processing dataset 'kdd_cup_2018_with_missing/H' (slug: kdd_cup_2018_with_missing_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'kdd_cup_2018_with_missing/H' (slug: kdd_cup_2018_with_missing_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 157.51it/s]

















1024it [00:06, 157.97it/s]


















1024it [00:06, 149.29it/s]


















1024it [00:06, 150.24it/s]


















1024it [00:06, 150.52it/s]






280it [00:01, 155.75it/s]








/home/roc/01_projects/01_timeseries/timeseries-research/src/multivar_timeseries/evaluation/metrics.py:35: RuntimeWarning: Mean of empty slice
  np.nanmean(series_slice, axis=series_slice.ndim - 1, keepdims=True)[0]




5400it [00:09, 590.56it/s]
2025-11-18 14:19:54 - INFO - OK saved results for 'kdd_cup_2018_with_missing/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/kdd_cup_2018_with_missing_H__short/Moirai-GiftEval/kdd_cup_2018_with_missing_H__short_results.csv (136.430s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'kdd_cup_2018_with_missing/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/kdd_cup_2018_with_missing_H__short/Moirai-GiftEval/kdd_cup_2018_with_missing_H__short_results.csv (136.430s)
2025-11-18 14:19:54 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:19:54 - INFO - Processing dataset 'LOOP_SEATTLE/5T' (slug: LOOP_SEATTLE_5T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'LOOP_SEATTLE/5T' (slug: LOOP_SEATTLE_5T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 158.08it/s]

















1024it [00:06, 157.57it/s]

















1024it [00:06, 157.36it/s]

















1024it [00:06, 158.00it/s]


















1024it [00:06, 150.44it/s]


















1024it [00:06, 150.61it/s]






316it [00:02, 155.37it/s]














6460it [01:12, 88.82it/s]
2025-11-18 14:23:39 - INFO - OK saved results for 'LOOP_SEATTLE/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_5T__short/Moirai-GiftEval/LOOP_SEATTLE_5T__short_results.csv (225.004s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'LOOP_SEATTLE/5T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_5T__short/Moirai-GiftEval/LOOP_SEATTLE_5T__short_results.csv (225.004s)
2025-11-18 14:23:39 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:23:39 - INFO - Processing dataset 'LOOP_SEATTLE/D' (slug: LOOP_SEATTLE_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'LOOP_SEATTLE/D' (slug: LOOP_SEATTLE_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

646it [00:04, 148.29it/s]


646it [00:00, 1452.24it/s]
2025-11-18 14:23:52 - INFO - OK saved results for 'LOOP_SEATTLE/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_D__short/Moirai-GiftEval/LOOP_SEATTLE_D__short_results.csv (12.531s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'LOOP_SEATTLE/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_D__short/Moirai-GiftEval/LOOP_SEATTLE_D__short_results.csv (12.531s)
2025-11-18 14:23:52 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:23:52 - INFO - Processing dataset 'LOOP_SEATTLE/H' (slug: LOOP_SEATTLE_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'LOOP_SEATTLE/H' (slug: LOOP_SEATTLE_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 152.27it/s]


















1024it [00:06, 151.71it/s]


















1024it [00:06, 151.73it/s]


















1024it [00:06, 151.28it/s]

















1024it [00:06, 157.52it/s]

















1017it [00:06, 157.83it/s]













6137it [00:09, 676.68it/s]
2025-11-18 14:26:24 - INFO - OK saved results for 'LOOP_SEATTLE/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_H__short/Moirai-GiftEval/LOOP_SEATTLE_H__short_results.csv (152.307s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'LOOP_SEATTLE/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/LOOP_SEATTLE_H__short/Moirai-GiftEval/LOOP_SEATTLE_H__short_results.csv (152.307s)
2025-11-18 14:26:24 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:26:24 - INFO - Processing dataset 'M_DENSE/D' (slug: M_DENSE_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'M_DENSE/D' (slug: M_DENSE_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

90it [00:00, 153.23it/s]

90it [00:00, 1257.09it/s]
2025-11-18 14:26:27 - INFO - OK saved results for 'M_DENSE/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/M_DENSE_D__short/Moirai-GiftEval/M_DENSE_D__short_results.csv (2.956s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'M_DENSE/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/M_DENSE_D__short/Moirai-GiftEval/M_DENSE_D__short_results.csv (2.956s)
2025-11-18 14:26:27 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:26:27 - INFO - Processing dataset 'M_DENSE/H' (slug: M_DENSE_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'M_DENSE/H' (slug: M_DENSE_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

600it [00:03, 158.53it/s]



600it [00:01, 421.93it/s]
2025-11-18 14:26:43 - INFO - OK saved results for 'M_DENSE/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/M_DENSE_H__short/Moirai-GiftEval/M_DENSE_H__short_results.csv (15.783s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'M_DENSE/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/M_DENSE_H__short/Moirai-GiftEval/M_DENSE_H__short_results.csv (15.783s)
2025-11-18 14:26:43 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:26:43 - INFO - Processing dataset 'SZ_TAXI/15T' (slug: SZ_TAXI_15T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'SZ_TAXI/15T' (slug: SZ_TAXI_15T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 158.64it/s]



68it [00:00, 146.20it/s]



1092it [00:00, 1153.52it/s]
2025-11-18 14:27:11 - INFO - OK saved results for 'SZ_TAXI/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/SZ_TAXI_15T__short/Moirai-GiftEval/SZ_TAXI_15T__short_results.csv (28.069s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'SZ_TAXI/15T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/SZ_TAXI_15T__short/Moirai-GiftEval/SZ_TAXI_15T__short_results.csv (28.069s)
2025-11-18 14:27:11 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:27:11 - INFO - Processing dataset 'SZ_TAXI/H' (slug: SZ_TAXI_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'SZ_TAXI/H' (slug: SZ_TAXI_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

312it [00:01, 156.07it/s]


312it [00:00, 1330.02it/s]
2025-11-18 14:27:19 - INFO - OK saved results for 'SZ_TAXI/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/SZ_TAXI_H__short/Moirai-GiftEval/SZ_TAXI_H__short_results.csv (8.430s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'SZ_TAXI/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/SZ_TAXI_H__short/Moirai-GiftEval/SZ_TAXI_H__short_results.csv (8.430s)
2025-11-18 14:27:19 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:27:19 - INFO - Processing dataset 'saugeenday/D' (slug: saugeenday_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'saugeenday/D' (slug: saugeenday_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

20it [00:00, 137.05it/s]

20it [00:00, 301.79it/s]
2025-11-18 14:27:21 - INFO - OK saved results for 'saugeenday/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_D__short/Moirai-GiftEval/saugeenday_D__short_results.csv (1.750s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'saugeenday/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_D__short/Moirai-GiftEval/saugeenday_D__short_results.csv (1.750s)
2025-11-18 14:27:21 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:27:21 - INFO - Processing dataset 'saugeenday/M' (slug: saugeenday_M__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'saugeenday/M' (slug: saugeenday_M__short)

Evaluating Datasets: 0it [00:00, ?it/s]

7it [00:00, 112.68it/s]

7it [00:00, 770.87it/s]
2025-11-18 14:27:22 - INFO - OK saved results for 'saugeenday/M' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_M__short/Moirai-GiftEval/saugeenday_M__short_results.csv (1.458s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'saugeenday/M' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_M__short/Moirai-GiftEval/saugeenday_M__short_results.csv (1.458s)
2025-11-18 14:27:22 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:27:22 - INFO - Processing dataset 'saugeenday/W' (slug: saugeenday_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'saugeenday/W' (slug: saugeenday_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

20it [00:00, 152.63it/s]

20it [00:00, 880.56it/s]
2025-11-18 14:27:24 - INFO - OK saved results for 'saugeenday/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_W__short/Moirai-GiftEval/saugeenday_W__short_results.csv (1.611s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'saugeenday/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/saugeenday_W__short/Moirai-GiftEval/saugeenday_W__short_results.csv (1.611s)
2025-11-18 14:27:24 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:27:24 - INFO - Processing dataset 'solar/10T' (slug: solar_10T__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'solar/10T' (slug: solar_10T__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 149.98it/s]

















1024it [00:06, 156.66it/s]












692it [00:04, 157.32it/s]







2740it [00:16, 167.16it/s]
2025-11-18 14:28:45 - INFO - OK saved results for 'solar/10T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_10T__short/Moirai-GiftEval/solar_10T__short_results.csv (81.071s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'solar/10T' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_10T__short/Moirai-GiftEval/solar_10T__short_results.csv (81.071s)
2025-11-18 14:28:45 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:28:45 - INFO - Processing dataset 'solar/D' (slug: solar_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'solar/D' (slug: solar_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

274it [00:02, 135.22it/s]


274it [00:00, 1458.25it/s]
2025-11-18 14:28:51 - INFO - OK saved results for 'solar/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_D__short/Moirai-GiftEval/solar_D__short_results.csv (6.336s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'solar/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_D__short/Moirai-GiftEval/solar_D__short_results.csv (6.336s)
2025-11-18 14:28:51 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:28:51 - INFO - Processing dataset 'solar/H' (slug: solar_H__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'solar/H' (slug: solar_H__short)

Evaluating Datasets: 0it [00:00, ?it/s]

1024it [00:06, 158.23it/s]

















1024it [00:06, 158.03it/s]










555it [00:03, 156.78it/s]






2603it [00:03, 697.09it/s]
2025-11-18 14:29:56 - INFO - OK saved results for 'solar/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_H__short/Moirai-GiftEval/solar_H__short_results.csv (65.004s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'solar/H' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_H__short/Moirai-GiftEval/solar_H__short_results.csv (65.004s)
2025-11-18 14:29:56 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:29:56 - INFO - Processing dataset 'solar/W' (slug: solar_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'solar/W' (slug: solar_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

137it [00:00, 154.22it/s]


137it [00:00, 1266.51it/s]
2025-11-18 14:29:59 - INFO - OK saved results for 'solar/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_W__short/Moirai-GiftEval/solar_W__short_results.csv (2.834s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'solar/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/solar_W__short/Moirai-GiftEval/solar_W__short_results.csv (2.834s)
2025-11-18 14:29:59 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:29:59 - INFO - Processing dataset 'us_births/D' (slug: us_births_D__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'us_births/D' (slug: us_births_D__short)

Evaluating Datasets: 0it [00:00, ?it/s]

20it [00:00, 135.36it/s]

20it [00:00, 662.92it/s]
2025-11-18 14:30:01 - INFO - OK saved results for 'us_births/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_D__short/Moirai-GiftEval/us_births_D__short_results.csv (1.700s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'us_births/D' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_D__short/Moirai-GiftEval/us_births_D__short_results.csv (1.700s)
2025-11-18 14:30:01 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:30:01 - INFO - Processing dataset 'us_births/M' (slug: us_births_M__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'us_births/M' (slug: us_births_M__short)

Evaluating Datasets: 0it [00:00, ?it/s]

2it [00:00, 58.48it/s]

2it [00:00, 377.44it/s]
2025-11-18 14:30:02 - INFO - OK saved results for 'us_births/M' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_M__short/Moirai-GiftEval/us_births_M__short_results.csv (1.367s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'us_births/M' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_M__short/Moirai-GiftEval/us_births_M__short_results.csv (1.367s)
2025-11-18 14:30:02 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:30:02 - INFO - Processing dataset 'us_births/W' (slug: us_births_W__short)
INFO:ts_toolkit.pipeline.dataset_batch_runner:Processing dataset 'us_births/W' (slug: us_births_W__short)

Evaluating Datasets: 0it [00:00, ?it/s]

14it [00:00, 151.82it/s]

14it [00:00, 1054.72it/s]
2025-11-18 14:30:04 - INFO - OK saved results for 'us_births/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_W__short/Moirai-GiftEval/us_births_W__short_results.csv (1.807s)
INFO:ts_toolkit.pipeline.dataset_batch_runner:OK saved results for 'us_births/W' to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/us_births_W__short/Moirai-GiftEval/us_births_W__short_results.csv (1.807s)
2025-11-18 14:30:04 - INFO - COMBINED results written to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/Moirai-GiftEval/combined_results.csv
INFO:ts_toolkit.pipeline.dataset_batch_runner:COMBINED results written to /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/Moirai-GiftEval/combined_results.csv
2025-11-18 14:30:04 - INFO - ----
INFO:ts_toolkit.pipeline.dataset_batch_runner:----
2025-11-18 14:30:04 - INFO - Run complete. 42 succeeded, 0 failed.
INFO:ts_toolkit.pipeline.dataset_batch_runner:Run complete. 42 succeeded, 0 failed.

Experiment completed.
  Config: configs/experiments/moirai_short_uni_512.yaml
  Successes: 42
  Failures: 0
  Combined results: /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/Moirai-GiftEval/combined_results.csv
  Log file: /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/dataset_run.log
  Summary: /home/roc/01_projects/01_timeseries/timeseries-research/results/moirai_short_uni_512_20251118-133809/dataset_run_summary.json

In [1]:
from ts_toolkit.pipeline.runner import TsPipeline
from ts_toolkit.pipeline.utils import load_config
import logging
from tqdm.notebook import tqdm
import pandas as pd
from dotenv import load_dotenv
import os

# auto reload imports in jupyter
%load_ext autoreload
%autoreload 2

/home/roc/01_projects/01_timeseries/timeseries-research/.venv/lib/python3.10/site-packages/fs/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore

In [2]:
load_dotenv()
print(GIFT_EVAL_PATH := os.getenv("GIFT_EVAL"))
print(REPO_ROOT := os.getenv("REPO_ROOT"))

/home/roc/01_projects/01_timeseries/timeseries-research/data/gift_eval
/home/roc/01_projects/01_timeseries/timeseries-research

In [ ]:
logging.basicConfig(level=logging.INFO)

# --- Load configuration ---
config_path = "configs/experiments/toto_short_uni_4096.yaml"

config = load_config(config_path)

# --- Set up the evaluation pipeline ---
pipeline = TsPipeline(config)
pipeline.run(skip_existing=False, num_visualization=5)

pipeline.get_results()

INFO:root:   - Results will be saved to: /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample
INFO:root:   - Datasets will be loaded from: /home/roc/01_projects/01_timeseries/timeseries-research/data/gift_eval

INFO:root:
--- Starting Evaluation ---

Loading base config from <REPO_ROOT>/configs/experiments/gifteval_mar_mbr_medium.yaml...

Evaluating Datasets:   0%|          | 0/41 [00:00<?, ?it/s]

100%|██████████| 16/16 [00:46<00:00,  2.91s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.95s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.97s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.97s/it]
















100%|██████████| 15/15 [00:42<00:00,  2.86s/it]











5000it [00:08, 623.65it/s]
INFO:ts_toolkit.pipeline.eval:Results for bitbrains_fast_storage/5T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml

















100%|██████████| 16/16 [00:47<00:00,  2.97s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]









100%|██████████| 8/8 [00:21<00:00,  2.74s/it]






2500it [00:02, 1172.92it/s]
INFO:ts_toolkit.pipeline.eval:Results for bitbrains_fast_storage/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml

















100%|██████████| 16/16 [00:47<00:00,  2.98s/it]

















100%|██████████| 16/16 [00:46<00:00,  2.88s/it]





2000it [00:03, 622.60it/s]
INFO:ts_toolkit.pipeline.eval:Results for bitbrains_rnd/5T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml

















100%|██████████| 16/16 [00:46<00:00,  2.93s/it]



1000it [00:00, 1174.22it/s]
INFO:ts_toolkit.pipeline.eval:Results for bitbrains_rnd/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:02<00:00,  2.48s/it]


49it [00:00, 249.16it/s]
INFO:ts_toolkit.pipeline.eval:Results for bizitobs_l2c/5T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:01<00:00,  1.44s/it]

7it [00:00, 600.74it/s]
INFO:ts_toolkit.pipeline.eval:Results for bizitobs_l2c/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml



100%|██████████| 2/2 [00:05<00:00,  2.61s/it]


105it [00:00, 132.35it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett1/15T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:00<00:00,  1.07it/s]

7it [00:00, 784.25it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett1/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:01<00:00,  1.83s/it]

28it [00:00, 398.47it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett1/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:00<00:00,  2.50it/s]

7it [00:00, 837.74it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett1/W have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml



100%|██████████| 2/2 [00:05<00:00,  2.63s/it]


105it [00:00, 129.23it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett2/15T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:00<00:00,  1.07it/s]

7it [00:00, 791.87it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett2/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:01<00:00,  1.85s/it]

28it [00:00, 402.88it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett2/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:00<00:00,  2.47it/s]

7it [00:00, 813.30it/s]
INFO:ts_toolkit.pipeline.eval:Results for ett2/W have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml





100%|██████████| 4/4 [00:11<00:00,  2.78s/it]


231it [00:01, 165.14it/s]
INFO:ts_toolkit.pipeline.eval:Results for jena_weather/10T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

21it [00:00, 1259.05it/s]
INFO:ts_toolkit.pipeline.eval:Results for jena_weather/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml


100%|██████████| 1/1 [00:02<00:00,  2.31s/it]

42it [00:00, 626.78it/s]
INFO:ts_toolkit.pipeline.eval:Results for jena_weather/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'electricity/15T' has target_dim=1 => to_univariate is forced set to False.

















100%|██████████| 16/16 [00:48<00:00,  3.01s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.95s/it]





100%|██████████| 4/4 [00:10<00:00,  2.73s/it]
















7400it [01:45, 70.07it/s]
INFO:ts_toolkit.pipeline.eval:Results for electricity/15T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'electricity/D' has target_dim=1 => to_univariate is forced set to False.







100%|██████████| 6/6 [00:12<00:00,  2.04s/it]


370it [00:00, 1038.65it/s]
INFO:ts_toolkit.pipeline.eval:Results for electricity/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'electricity/H' has target_dim=1 => to_univariate is forced set to False.

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]
















100%|██████████| 15/15 [00:42<00:00,  2.86s/it]







2960it [00:12, 240.00it/s]
INFO:ts_toolkit.pipeline.eval:Results for electricity/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'electricity/W' has target_dim=1 => to_univariate is forced set to False.







100%|██████████| 6/6 [00:07<00:00,  1.26s/it]


370it [00:00, 1287.00it/s]
INFO:ts_toolkit.pipeline.eval:Results for electricity/W have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'hierarchical_sales/D' has target_dim=1 => to_univariate is forced set to False.



100%|██████████| 2/2 [00:03<00:00,  2.00s/it]


118it [00:00, 1002.18it/s]
INFO:ts_toolkit.pipeline.eval:Results for hierarchical_sales/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'hierarchical_sales/W' has target_dim=1 => to_univariate is forced set to False.



100%|██████████| 2/2 [00:02<00:00,  1.23s/it]

118it [00:00, 1197.18it/s]
INFO:ts_toolkit.pipeline.eval:Results for hierarchical_sales/W have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'kdd_cup_2018_with_missing/D' has target_dim=1 => to_univariate is forced set to False.






100%|██████████| 5/5 [00:09<00:00,  1.90s/it]


270it [00:00, 1213.78it/s]
INFO:ts_toolkit.pipeline.eval:Results for kdd_cup_2018_with_missing/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'kdd_cup_2018_with_missing/H' has target_dim=1 => to_univariate is forced set to False.










100%|██████████| 9/9 [00:25<00:00,  2.85s/it]


540it [00:01, 530.49it/s]
INFO:ts_toolkit.pipeline.eval:Results for kdd_cup_2018_with_missing/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'LOOP_SEATTLE/5T' has target_dim=1 => to_univariate is forced set to False.

















100%|██████████| 16/16 [00:47<00:00,  2.98s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]

















100%|██████████| 16/16 [00:47<00:00,  2.96s/it]






100%|██████████| 5/5 [00:14<00:00,  2.89s/it]














6460it [01:08, 93.76it/s]
INFO:ts_toolkit.pipeline.eval:Results for LOOP_SEATTLE/5T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'LOOP_SEATTLE/D' has target_dim=1 => to_univariate is forced set to False.







100%|██████████| 6/6 [00:11<00:00,  1.89s/it]


323it [00:00, 1242.39it/s]
INFO:ts_toolkit.pipeline.eval:Results for LOOP_SEATTLE/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'LOOP_SEATTLE/H' has target_dim=1 => to_univariate is forced set to False.












100%|██████████| 11/11 [00:30<00:00,  2.81s/it]



646it [00:01, 629.72it/s]
INFO:ts_toolkit.pipeline.eval:Results for LOOP_SEATTLE/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'M_DENSE/D' has target_dim=1 => to_univariate is forced set to False.


100%|██████████| 1/1 [00:01<00:00,  1.31s/it]

30it [00:00, 845.48it/s]
INFO:ts_toolkit.pipeline.eval:Results for M_DENSE/D have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'M_DENSE/H' has target_dim=1 => to_univariate is forced set to False.



100%|██████████| 2/2 [00:05<00:00,  2.79s/it]


120it [00:00, 399.43it/s]
INFO:ts_toolkit.pipeline.eval:Results for M_DENSE/H have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'SZ_TAXI/15T' has target_dim=1 => to_univariate is forced set to False.




100%|██████████| 3/3 [00:07<00:00,  2.57s/it]


156it [00:00, 915.20it/s]
INFO:ts_toolkit.pipeline.eval:Results for SZ_TAXI/15T have been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/all_results.csv
INFO:ts_toolkit.pipeline.eval:Config has been written to /home/roc/01_projects/01_timeseries/timeseries-research/results/gift_eval_mar_mbr_medium_20251017-233231/ToTo-GiftEval-sample/gift_eval_mar_mbr_medium_20251017-233231_config.yaml
INFO:ts_toolkit.pipeline.eval:Dataset 'SZ_TAXI/H' has target_dim=1 => to_univariate is forced set to False.




100%|██████████| 3/3 [00:07<00:00,  2.57s/it]


156it [00:00, 1135.54it/s]

,dataset,variate,num_variates,model,eval_metrics/MAR[0.5][512],eval_metrics/MBR[0.5][512],eval_metrics/MSE[mean],eval_metrics/MSE[0.5],eval_metrics/MAE[0.5],eval_metrics/MASE[0.5],eval_metrics/MAPE[0.5],eval_metrics/sMAPE[0.5],eval_metrics/MSIS,eval_metrics/RMSE[mean],eval_metrics/NRMSE[mean],eval_metrics/ND[0.5],eval_metrics/mean_weighted_sum_quantile_loss
0,bitbrains_fast_storage/5T/medium,UNI,2,ToTo-GiftEval-sample,1.699734,0.661208,3.539412e+06,3.539412e+06,278.856661,1.028482,4.191768e+00,0.811069,24.440409,1881.332614,5.716008,0.847244,0.624484
1,bitbrains_fast_storage/H/medium,UNI,2,ToTo-GiftEval-sample,2.064545,0.788567,6.817993e+06,6.817993e+06,542.080344,2.643465,4.820011e+00,0.683188,64.515813,2611.128608,4.219193,0.875921,0.644773
2,bitbrains_rnd/5T/medium,UNI,2,ToTo-GiftEval-sample,1.576620,0.665181,2.274758e+06,2.274758e+06,148.663151,4.551482,4.101124e-01,0.720478,166.674949,1508.230129,6.345893,0.625502,0.592661
3,bitbrains_rnd/H/medium,UNI,2,ToTo-GiftEval-sample,1.611902,0.706109,2.928786e+06,2.928786e+06,261.824378,4.603279,2.339533e+00,0.725559,150.484120,1711.369484,5.524020,0.845126,0.934721
4,bizitobs_l2c/5T/medium,UNI,7,ToTo-GiftEval-sample,1.514166,0.751063,1.847149e+02,1.847149e+02,9.541071,0.905631,6.187130e-01,0.966998,12.497039,13.590986,0.715086,0.502001,0.424842
5,bizitobs_l2c/H/medium,UNI,7,ToTo-GiftEval-sample,1.344597,0.794940,3.344805e+02,3.344805e+02,12.290312,1.186023,8.426340e-01,1.290753,8.773255,18.288807,1.107415,0.744197,0.536346
6,ett1/15T/medium,UNI,7,ToTo-GiftEval-sample,1.366755,0.739782,1.348250e+01,1.348250e+01,1.884763,1.202659,7.794023e-01,0.446124,10.030287,3.671853,0.699859,0.359238,0.284735
7,ett1/D/medium,UNI,7,ToTo-GiftEval-sample,1.699571,0.864286,9.047125e+04,9.047125e+04,201.634519,2.438434,1.541626e+00,0.719169,17.948637,300.784396,0.829669,0.556179,0.419967
8,ett1/H/medium,UNI,7,ToTo-GiftEval-sample,1.031102,0.706250,1.544519e+02,1.544519e+02,6.928714,1.298721,4.872703e+12,0.456627,10.154300,12.427869,0.595265,0.331869,0.264588
9,ett1/W/medium,UNI,7,ToTo-GiftEval-sample,1.388638,0.782143,4.124539e+06,4.124539e+06,1389.082965,2.388871,1.480090e+00,0.636271,21.210158,2030.896216,0.753931,0.515670,0.421298
10,ett2/15T/medium,UNI,7,ToTo-GiftEval-sample,2.063017,0.845198,1.660449e+01,1.660449e+01,2.599854,1.083269,1.673568e-01,0.196449,7.595819,4.074861,0.217157,0.138551,0.107057
11,ett2/D/medium,UNI,7,ToTo-GiftEval-sample,2.729198,0.845714,4.857154e+05,4.857154e+05,542.516174,4.635488,5.090283e+00,0.592388,39.696471,696.932866,0.442924,0.344787,0.271634
12,ett2/H/medium,UNI,7,ToTo-GiftEval-sample,1.879782,0.788616,2.564025e+02,2.564025e+02,9.887381,1.062016,1.737332e-01,0.173890,7.567500,16.012573,0.215780,0.133239,0.107141
13,ett2/W/medium,UNI,7,ToTo-GiftEval-sample,0.991733,0.712500,6.430320e+07,6.430320e+07,5355.163430,9.131100,4.371209e+00,0.836243,199.903290,8018.927585,0.642562,0.429113,0.343633
14,jena_weather/10T/medium,UNI,21,ToTo-GiftEval-sample,1.405239,0.769661,1.848270e+03,1.848270e+03,10.918075,0.660539,6.810064e-01,0.695034,6.790172,42.991514,0.263838,0.067004,0.057873
15,jena_weather/D/medium,UNI,21,ToTo-GiftEval-sample,4.373738,0.897302,8.260203e+03,8.260203e+03,35.030335,3.142759,7.178252e-01,0.599831,37.585769,90.885658,0.469266,0.180870,0.151197
16,jena_weather/H/medium,UNI,21,ToTo-GiftEval-sample,1.385140,0.832688,1.281539e+03,1.281539e+03,10.281464,0.841796,1.886814e+00,0.700971,7.940708,35.798591,0.219058,0.062914,0.051312
17,electricity/15T/medium,UNI,1,ToTo-GiftEval-sample,1.047713,0.625639,3.247344e+05,3.247344e+05,72.076588,1.188908,1.930090e-01,0.190671,10.930169,569.854759,0.981917,0.124195,0.101285
18,electricity/D/medium,UNI,1,ToTo-GiftEval-sample,1.382095,0.741812,5.859975e+09,5.859975e+09,8918.039273,2.562655,3.582535e-01,0.169001,23.949105,76550.473377,1.274888,0.148523,0.114942
19,electricity/H/medium,UNI,1,ToTo-GiftEval-sample,0.979056,0.577879,7.238521e+06,7.238521e+06,261.121627,1.135759,2.075514e-01,0.138007,10.248087,2690.449927,1.050171,0.101924,0.082371
20,electricity/W/medium,UNI,1,ToTo-GiftEval-sample,1.247139,0.784076,5.761346e+11,5.761346e+11,84057.093051,3.145702,4.592058e-01,0.266873,33.668712,759035.319317,1.754683,0.194317,0.154344
21,hierarchical_sales/D/medium,UNI,1,ToTo-GiftEval-sample,1.986058,0.856719,2.912190e+01,2.912190e+01,2.317369,0.744325,6.159416e-01,1.034062,7.714768,5.396471,1.642854,0.705479,0.580660
22,hierarchical_sales/W/medium,UNI,1,ToTo-GiftEval-sample,1.784058,0.826589,1.028980e+03,1.028980e+03,10.858064,0.809770,6.383442e-01,0.479995,7.857740,32.077720,1.358500,0.459842,0.392813
23,kdd_cup_2018_with_missing/D/medium,UNI,1,ToTo-GiftEval-sample,2.207036,0.846301,1.202853e+03,1.202853e+03,18.622578,0.966574,9.386557e-01,0.526084,9.065145,34.682167,0.946751,0.508357,0.408559
24,kdd_cup_2018_with_missing/H/medium,UNI,1,ToTo-GiftEval-sample,2.593487,0.854133,5.072452e+03,5.072452e+03,25.617749,1.069477,9.125260e-01,0.577055,12.026789,71.221152,1.490788,0.536226,0.439508
25,LOOP_SEATTLE/5T/medium,UNI,1,ToTo-GiftEval-sample,1.507802,0.778037,1.429918e+02,1.429918e+02,7.105890,1.109744,2.408360e-01,0.155754,11.418856,11.957919,0.212756,0.126428,0.103677
26,LOOP_SEATTLE/D/medium,UNI,1,ToTo-GiftEval-sample,2.602203,0.891135,1.744788e+01,1.744788e+01,3.075458,0.980158,5.784696e-02,0.056014,7.795905,4.177066,0.074044,0.054517,0.043099
27,LOOP_SEATTLE/H/medium,UNI,1,ToTo-GiftEval-sample,1.121476,0.677603,8.422492e+01,8.422492e+01,5.160035,1.057783,1.446715e-01,0.116431,9.354167,9.177413,0.162210,0.091203,0.073986
28,M_DENSE/D/medium,UNI,1,ToTo-GiftEval-sample,1.660742,0.764444,2.015926e+04,2.015926e+04,64.133072,0.863354,1.614828e-01,0.131698,8.162964,141.983305,0.255303,0.115319,0.097057
29,M_DENSE/H/medium,UNI,1,ToTo-GiftEval-sample,1.047452,0.614462,3.891542e+04,3.891542e+04,88.755127,0.757058,2.828833e-01,0.211379,7.468490,197.269917,0.343225,0.154423,0.126542
30,SZ_TAXI/15T/medium,UNI,1,ToTo-GiftEval-sample,4.142176,0.912914,1.767826e+01,1.767826e+01,2.874037,0.560198,1.211872e+13,0.416950,4.280211,4.204552,0.391304,0.267477,0.211714
31,SZ_TAXI/H/medium,UNI,1,ToTo-GiftEval-sample,1.816652,0.886886,3.213148e+01,3.213148e+01,4.354468,0.885513,3.139608e+00,0.513169,8.560067,5.668463,0.520439,0.399797,0.323401
32,saugeenday/D/medium,UNI,1,ToTo-GiftEval-sample,1.481415,0.589167,2.149980e+03,2.149980e+03,20.335151,4.555699,5.180445e-01,0.588294,65.579298,46.367879,1.448951,0.635454,0.559147
33,saugeenday/M/medium,UNI,1,ToTo-GiftEval-sample,1.186668,0.658333,3.227022e+02,3.227022e+02,11.038586,0.628552,3.388959e-01,0.332707,4.587973,17.963913,0.567663,0.348822,0.280260
34,saugeenday/W/medium,UNI,1,ToTo-GiftEval-sample,1.772288,0.752500,1.225003e+03,1.225003e+03,16.338312,1.339668,4.194764e-01,0.433892,11.361436,35.000042,1.086316,0.507101,0.412486
35,solar/10T/medium,UNI,1,ToTo-GiftEval-sample,1.237216,0.741181,4.570927e+01,4.570927e+01,3.048509,1.341378,1.788976e+00,1.671596,18.156779,6.760863,1.500262,0.676476,0.604612
36,solar/D/medium,UNI,1,ToTo-GiftEval-sample,2.451496,0.888954,1.321834e+05,1.321834e+05,280.247806,0.811182,5.437913e-01,0.338880,7.406829,363.570311,0.381789,0.294291,0.241970
37,solar/H/medium,UNI,1,ToTo-GiftEval-sample,0.819677,0.709573,1.112888e+03,1.112888e+03,13.035413,1.001512,4.435049e+00,1.423866,11.953529,33.359972,1.201704,0.469566,0.397283
38,us_births/D/medium,UNI,1,ToTo-GiftEval-sample,1.073604,0.565556,3.764511e+05,3.764511e+05,447.011756,0.667920,4.277424e-02,0.042622,6.122371,613.556147,0.058144,0.042361,0.034750
39,us_births/M/medium,UNI,1,ToTo-GiftEval-sample,2.677673,0.991667,6.507328e+08,6.507328e+08,21367.316927,1.957536,6.755984e-02,0.070838,15.456214,25509.464905,0.082717,0.069285,0.050468
0,us_births/W/medium,UNI,1,ToTo-GiftEval-sample,1.136211,0.681250,3.985658e+06,3.985658e+06,1529.786963,1.399018,2.058789e-02,0.020710,8.944573,1996.411378,0.027246,0.020878,0.015960

In [ ]:
config.experiment_name

'gift_eval_mar_mbr_full_20251017-171624'

In [ ]:
import pandas as pd
df_results = pd.read_csv(f"{REPO_ROOT}/results/{config.experiment_name}/{config.forecaster.alias}/all_results.csv")
df_results

,dataset,variate,num_variates,model,eval_metrics/MSE[mean],eval_metrics/MSE[0.5],eval_metrics/MAE[0.5],eval_metrics/MASE[0.5],eval_metrics/MAPE[0.5],eval_metrics/sMAPE[0.5],...,eval_metrics/MSE[0.5]_all,eval_metrics/MAE[0.5]_all,eval_metrics/MASE[0.5]_all,eval_metrics/MAPE[0.5]_all,eval_metrics/sMAPE[0.5]_all,eval_metrics/MSIS_all,eval_metrics/RMSE[mean]_all,eval_metrics/NRMSE[mean]_all,eval_metrics/ND[0.5]_all,eval_metrics/mean_weighted_sum_quantile_loss_all
0,bizitobs_l2c/H,MULTI,7,ToTo-GiftEval-sample,440.043383,440.043383,16.191903,2.25185,2.137929,1.505732,...,0 440.043383\n1 429.468347\n2 422....,0 16.191903\n1 16.049746\n2 15.867...,0 2.251850\n1 2.203547\n2 2.142641...,0 2.137929\n1 1.707162\n2 1.314620...,0 1.505732\n1 1.492889\n2 1.450249...,0 77.151851\n1 67.392044\n2 54.383...,0 20.977211\n1 20.723618\n2 20.552...,0 1.456277\n1 1.427518\n2 1.395066...,0 1.124072\n1 1.105564\n2 1.077096...,0 1.094789\n1 1.055535\n2 1.007165...

In [16]:
df_results['eval_metrics/MAE[0.5]_all'][0]

'0     16.191903\n1     16.049746\n2     15.867692\n3     15.939789\n4     15.868829\n5     15.185202\n6     14.575236\n7     14.057790\n8     14.385968\n9     14.349109\n10    14.523529\n11    14.199871\n12    14.396627\n13    14.333341\n14    15.398176\n15    15.441875\n16    15.324949\n17    14.658757\n18    14.170233\n19    14.153216\n20    14.340941\n21    14.374166\n22    14.005002\n23    14.305349\n24    14.234480\n25    14.220032\n26    12.959763\n27    12.903173\n28    12.240773\n29    12.451297\n30    12.169081\n31    12.634473\n32    13.475215\n33    13.666390\n34    14.425859\n35    14.369735\n36    14.225695\n37    14.401274\n38    14.408903\n39    14.934228\n40    15.064535\n41    15.496502\n42    15.765365\n43    15.789291\n44    15.147556\n45    15.963046\n46    15.585856\n47    15.159534\nName: MAE[0.5], dtype: float64'

In [18]:
config.evaluation.to_univariate

False